config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "entries#index"
  resources :truck_details
  resources :payment_receipts
  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end
  resources :parties, concerns: :paginatable do
    resources :opening_balances
  end
  get 'parties/party_by_code/:party_code', to: 'parties#party_by_code'
  resources :party_invoices, concerns: :paginatable do
    member do
      patch :unlock
      put :unlock
    end
    resources :bills
    get 'download', on: :member, to: 'downloads#party_invoice_show'
  end
  get 'download_statement', to: 'downloads#invoice_statement_show'
  get 'download_expenses', to: 'downloads#expenses_show'
  get 'download_ledger', to: 'downloads#ledger_show'
  get 'download_parties_balance', to: 'downloads#balance_for_parties'
  resources :entries, concerns: :paginatable do
    resource :download, only: [:show]
    resources :payment_summaries
    resources :bill_entries
    resources :bills
    collection do
      get 'search'
    end
    get 'download', on: :member
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/party.rb
class Party < ApplicationRecord
  validates :party_name, presence: true,
            length: { maximum: 40 }, uniqueness: true
  validates :party_code, presence: true,
            length: { maximum: 15 }, uniqueness: true
  validates :gst_in, presence: true,
            length: { maximum: 15 }, uniqueness: true
  validates :address, presence: true,
            length: { maximum: 80 }

  has_many :payment_receipts
  has_many :opening_balances


  def calculate_current_balance(from_date, to_date)
    from_date = DateTime.parse(from_date)
    to_date = DateTime.parse(to_date)
    opening_balance = self.opening_balances.select { |opening_balance|
      (from_date.month < 4 && opening_balance.year == from_date.year - 1) || (from_date.month >= 4 && opening_balance.year == from_date.year)
    }
    if !opening_balance.any?
      return 0
    end
    balance = opening_balance[0].balance
    from_date_for_data = DateTime.new(opening_balance[0].year, 4, 1)
    payments = PaymentReceipt.where(:party_code => party_code, :date => from_date_for_data..to_date).order(date: :asc)
    party_invoices = PartyInvoice.where(:party_code => party_code, :date => from_date_for_data..to_date, :invoice_generated => true).order(date: :asc)
    payments.each do |payment|
      balance = balance - payment.amount
    end

    party_invoices.each do |party_invoice|
      balance = balance + (party_invoice.freight_total - (party_invoice.freight_total * party_invoice.bills[0].tds_percentage / 100))
    end
    balance
  end


  def calculate_balance_till_date(date)
    to_date = DateTime.parse(date)
    opening_balance = self.opening_balances.select { |opening_balance|
      (to_date.month < 4 && opening_balance.year == to_date.year - 1) || (to_date.month >= 4 && opening_balance.year == to_date.year)
    }
    if !opening_balance.any?
      return 0
    end
    balance = opening_balance[0].balance
    from_date_for_data = DateTime.new(opening_balance[0].year, 4, 1)
    payments = PaymentReceipt.where(:party_code => party_code, :date => from_date_for_data..to_date).order(date: :asc)
    party_invoices = PartyInvoice.where(:party_code => party_code, :date => from_date_for_data..to_date, :invoice_generated => true).order(date: :asc)
    payments.each do |payment|
      balance = balance - payment.amount
    end

    party_invoices.each do |party_invoice|
      balance = balance + (party_invoice.freight_total - (party_invoice.freight_total * party_invoice.bills[0].tds_percentage / 100))
    end
    balance
  end
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  before_action :authenticate_user!
  def index
    @parties = Party.order(:party_code).page params[:page]
  end

  def new
    @party = Party.new
  end

  def show
    @party = Party.find(params[:id])
  end

  def create
    @party = Party.new(party_params)

    if @party.save
      redirect_to @party
    else
      render 'new'
    end
  end

  def edit
    @party = Party.find(params[:id])
  end

  def update
    @party = Party.find(params[:id])

    if @party.update(party_params)
      redirect_to @party
    else
      render 'edit'
    end
  end

  def destroy
    @party = Party.find(params[:id])
    @party.destroy

    redirect_to parties_path
  end

  def party_by_code
    @party = Party.find_by_party_code(params[:party_code])
    render json: @party
  end

  private
  def party_params
    params.require(:party).permit!
  end
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/views/parties/_list.html.erb
<% if !@parties.nil? and !@parties.empty? %>
  <table class="table table-striped">
    <thead>
    <tr>
      <th>Party Name</th>
      <th>Party Code</th>
      <th>GSTIN</th>
      <th colspan="2"></th>
    </tr>
    </thead>

    <tbody>
    <% @parties.each do |party| %>
        <tr>
          <td><%= party.party_name %></td>
          <td><%= party.party_code %></td>
          <td><%= party.gst_in %></td>
          <td align="center"><%= link_to 'Show', party_path(party), class: 'button small radius' %></td>
          <td><%= link_to 'Edit', edit_party_path(party), class: 'button small radius' %></td>
          <td><%= link_to 'Destroy', party_path(party),
                          method: :delete,
                          data: { confirm: 'Are you sure?' }, class: 'button small radius'%></td>
        </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <p>No Parties to Display</p>
<% end %>

app/views/parties/balance_for_parties_pdf.erb
<div class="party-invoice">
  <div class="party-invoice-content">
    <div class="company-details">
      <h1 class="text-center company-name">JMR LOGISTICS</h1>
      <h3 class="text-center head-office">HEAD OFFICE</h3>
      <h4 class="text-center office-details">Shop No 15, Palla More, Old GT Road, Near Wine Shop, Alipur, Delhi-110036</h4>
      <h4 class="text-center office-details">E-mail: jmrlogistics16@gmail.com</h4>
      <h4 class="text-center office-details">Phone: 9212666550, 9910680644, 9999778668</h4>
      <h4 class="text-center report-title">Balance Statement from <%= from_date %> to <%= to_date %></h4>
    </div>
  </div>
  <div class="big-font space-mx invoice-statement">
    <table class="table table-condensed">
      <tbody>
      <tr class="table-header">
        <td>Party Code</td>
        <td>Party Name</td>
        <td>Balance (Rs)</td>
      </tr>
      <% parties.each do |party| %>
        <% current_party_balance = party.calculate_current_balance(from_date, to_date) %>

        <% if current_party_balance != 0  %>
          <tr>
            <td><%= party.party_code %></td>
            <td><span style="float:left; padding-left:5px;"><%= party.party_name %></span></td>
            <td><span style="float:right; padding-right:5px;"><%= number_to_indian_currency(current_party_balance, text: '') %></span></td>
          </tr>
        <% end %>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/parties/edit.html.erb
<div class="jumbotron">
  <div class="heading">
    <h3>Edit Party</h3>
  </div>

  <%= form_for :party, url: party_path(@party), method: :patch do |f| %>
      <div class="row shift">
        <%= f.label :party_name %>
        <%= f.text_field :party_name, class: "form-control" %>
      </div>

      <div class="row shift">
        <%= f.label :party_code %>
        <%= f.text_field :party_code, class: "form-control" %>
      </div>

      <div class="row shift">
        <%= f.label :gst_in %>
        <%= f.text_field :gst_in, class: "form-control" %>
      </div>

      <div class="row shift">
        <%= f.label :address %>
        <%= f.text_field :address, class: "form-control" %>
      </div>

      <%= link_to 'Back', parties_path, class: "btn btn-lg btn-primary" %>
      <%= f.submit class: "btn btn-lg btn-primary"%>

  <% end %>
</div>

app/views/parties/index.html.erb
<div class="jumbotron space">
  <ul class="dropdown-menu search_by" aria-labelledby="dropdownMenu3">
    <li class="dropdown-header">Dropdown header</li>
  </ul>
  <h3>Parties</h3>
  <%= render 'parties/list' %>
  <%= paginate @parties %>
  <div>
    <%= page_entries_info @parties %>
  </div>
</div>

app/views/parties/ledger_pdf.erb
<div class="party-invoice">
  <div class="expense-statement-content">
    <div class="company-details">
      <h1 class="text-center company-name">JMR LOGISTICS</h1>
      <h3 class="text-center head-office">HEAD OFFICE</h3>
      <h4 class="text-center office-details">Shop No 15, Palla More, Old GT Road, Near Wine Shop, Alipur, Delhi-110036</h4>
      <h4 class="text-center office-details">E-mail: jmrlogistics16@gmail.com</h4>
      <h4 class="text-center office-details">Phone: 9212666550, 9910680644, 9999778668</h4>
      <h3 class="text-center head-office"><%= party.party_name %></h3>

      <h4 class="text-center report-title">Ledger Account</h4>
    </div>
  </div>
  <div class="big-font space-mx invoice-statement">
    <table class="table table-condensed">
      <tbody>
      <tr class="table-header">
        <td >Date</td>
        <td >Particular</td>
        <td >Amount (Rs)</td>
        <td >TDS (Rs)</td>
        <td >Debit</td>
        <td >Credit</td>
        <td >Balance</td>
      </tr>
      <tr>
        <td></td>
        <td>Opening Balance </td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td><%= balance %> </td>
      </tr>
      <% payments.each do |payment| %>
        <% if payment.instance_of? PartyInvoice %>
          <tr>
            <td><%= payment.date %></td>
            <td class="ledger-particular" style="white-space:pre-wrap; word-wrap:break-word"> Freight Forward; Bill No. - <%= payment.invoice_number %>
 G.R. No. - <%= payment.get_all_gr_numbers %> </td>
            <td><%= payment.freight_total %></td>
            <td><%= (payment.freight_total * payment.bills[0].tds_percentage/100) %> </td>
            <td><%= payment.freight_total - (payment.freight_total * payment.bills[0].tds_percentage/100)%></td>
            <td></td>
            <td><%= balance = (balance + (payment.freight_total - (payment.freight_total * payment.bills[0].tds_percentage/100)))%> </td>
          </tr>
        <% elsif payment.instance_of? PaymentReceipt %>
          <tr>
            <td><%= payment.date %></td>
            <td class="ledger-particular"> <%= payment.depository_bank %>;  Mode: <%= payment.mode_of_payment %>
            <% if "cheque".eql? payment.mode_of_payment %>
              ; Cheque No: <%= payment.cheque_number %>
                <% end %></td>
            <td></td>
            <td></td>
            <td></td>
            <td><%= payment.amount %></td>
            <td><%= balance = (balance - payment.amount) %></td>
          </tr>
        <% end %>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/parties/new.html.erb
<div class="jumbotron">
  <div class="heading">
    <h3>Add Party</h3>
  </div>
  <%= form_for :party, url: parties_path do |f| %>
      <% if @party.errors.any? %>
          <div id="error_explanation">
            Please enter valid values
            <ul>
              <% @party.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
      <div class="row shift">
        <%= f.label :party_name %>
        <%= f.text_field :party_name, class: "form-control" %>
      </div>

      <div class="row shift">
        <%= f.label :party_code %>
        <%= f.text_field :party_code, class: "form-control" %>
      </div>

      <div class="row shift">
        <%= f.label :gst_in %>
        <%= f.text_field :gst_in, class: "form-control" %>
      </div>

      <div class="row shift">
        <%= f.label :address %>
        <%= f.text_field :address, class: "form-control" %>
      </div>

      <%= link_to 'Back', parties_path, class: 'btn btn-lg btn-primary' %>
      <%= f.submit class: "btn btn-lg btn-primary"%>
  <% end %>

</div>

app/views/parties/show.html.erb
<div class="jumbotron">
  <div class="heading-2">
    <h4>Party</h4>
  </div>
  <div class="show">
    <table class="table table-striped">
      <tr>
        <td class="row-right">
          <strong>Party Name:</strong>
        </td>
        <td>
          <%= @party.party_name%>

        </td>
        <td class="row-right">
          <strong>Party Code:</strong>
        </td>
        <td>
          <%= @party.party_code %>
        </td>
      </tr>
      <tr>
        <td class="row-right">
          <strong>GSTIN:</strong>
        </td>
        <td>
          <%= @party.gst_in %>
        </td>
        <td class="row-right">
          <strong>Address:</strong>
        </td>
        <td>
          <%= @party.address %>
        </td>
      </tr>
    </table>

    <div style="text-align:right;width:100%">
    <span style="float:left">
      <h5>Opening Balances</h5>
    </span>
      <p style="float:right; font-size:13px;"><%= link_to 'Add Opening Balance', new_party_opening_balance_path(@party.id) %></p>
    </div>
    <% if @party.opening_balances.empty? %>
      <div class="no-record">
        No Opening Balances for this party yet.
      </div>
    <% else %>
      <table class="table table-striped">
        <thead>
        <tr>
          <th>Year</th>
          <th>Balance</th>
          <th colspan="2"></th>
        </tr>
        </thead>
        <% @party.opening_balances.each do |opening_balance| %>
          <tr>
            <td><%= opening_balance.year %></td>
            <td><%= number_to_indian_currency(opening_balance.balance, text: 'Rs ') %></td>
            <% if current_user.admin? %>
              <td align="center"><%= link_to 'Edit', edit_party_opening_balance_path(@party.id, opening_balance), class: 'button small radius' %></td>
            <% end %>
          </tr>
        <% end %>
      </table>
    <% end %>

  </div>
  <%= link_to 'Back', parties_path, class: "btn btn-lg btn-primary" %>
</div>