config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "entries#index"
  resources :truck_details
  resources :payment_receipts
  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end
  resources :parties, concerns: :paginatable do
    resources :opening_balances
  end
  get 'parties/party_by_code/:party_code', to: 'parties#party_by_code'
  resources :party_invoices, concerns: :paginatable do
    member do
      patch :unlock
      put :unlock
    end
    resources :bills
    get 'download', on: :member, to: 'downloads#party_invoice_show'
  end
  get 'download_statement', to: 'downloads#invoice_statement_show'
  get 'download_expenses', to: 'downloads#expenses_show'
  get 'download_ledger', to: 'downloads#ledger_show'
  get 'download_parties_balance', to: 'downloads#balance_for_parties'
  resources :entries, concerns: :paginatable do
    resource :download, only: [:show]
    resources :payment_summaries
    resources :bill_entries
    resources :bills
    collection do
      get 'search'
    end
    get 'download', on: :member
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/entry.rb
class Entry < ApplicationRecord
  validates :truck_number, presence: true,
            length: { maximum: 15 }
  validates :station, presence: true,
            length: { maximum: 15 }
  validates :truck_owner, length: { maximum: 25 }
  validates :rate1, presence: true, numericality: true
  validates :rate2, presence: true, numericality: true
  validates :self_advance_1, presence: true, numericality: true
  validates :party_advance_2, presence: true, numericality: true
  validates :commission, presence: true, numericality: true
  validates :party_code, presence: true, length: { maximum: 15 }
  validate :check_truck_number_is_present
  validate :check_party_code_is_present
  has_one :payment_summary, dependent: :destroy
  has_one :bill, dependent: :destroy

  # , format: {with: ''}

  def freight2
    ((payment_summary.weight * rate2) + payment_summary.kanta).to_i
  end

  def freight1
    ((payment_summary.weight * rate1) + payment_summary.kanta).to_i
  end

  def firm_name
    if(!party_code.nil?)
      Party.find_by_party_code(party_code).party_name
    else
      firm
    end
  end

  def get_truck_owner
    TruckDetails.find_by_truck_number(self.truck_number).truck_owner
  end

  def cash_to_driver
    (freight1 * 4) / 100
  end

  def paid_to_truck_owner
    freight1 - self_advance_1 - cash_to_driver - commission - payment_summary.shortage2 - payment_summary.payment_charges
  end

  def self.search(truck_number, date)
    if truck_number and !date.present?
      where('truck_number LIKE ?', "%#{truck_number}%")
    elsif truck_number and date
      where('truck_number LIKE ? and entry_date = ?', "%#{truck_number}%", date.to_date)
    else
      all
    end
  end

  def set_invoice_number
    if self.invoice_number.nil?
      entries = Entry.where(company: self.company)
      if entries.maximum(:invoice_number).nil?
        self.invoice_number = 1
      else
        self.invoice_number = entries.maximum(:invoice_number) + 1
      end
      save
    end

  end

  def set_invoice_date
    if self.invoice_date.nil?
        self.invoice_date = Date.today
      save
    end
  end

  def set_company(company)
    if self.company.nil?
      self.company = company
      save
    end
  end

  def self.entries_without_gr_entry_between(start_date, end_date)
    entries_witout_gr_entry = Array.new
    entries = where(entry_date: start_date.to_date..end_date.to_date)
    entries.each do |entry|
      entries_witout_gr_entry.push(entry) if !entry.payment_summary.present?
    end
    entries_witout_gr_entry
  end

  def self.entries_without_bill_between(start_date, end_date)
    entries_without_bill = Array.new
    entries = where(entry_date: start_date.to_date..end_date.to_date)
    entries.each do |entry|
      entries_without_bill.push(entry) if !entry.bill.present?
    end
    entries_without_bill
  end

  def self.entries_with_invoice_number(invoice_number)
    if invoice_number
      where(invoice_number: invoice_number)
    end
  end

  def check_truck_number_is_present
    truck_details = TruckDetails.find_by_truck_number(self.truck_number)
    if(truck_details.blank?)
      self.errors.add(:truck_number, "add truck details for this truck number first")
    end
  end

  def check_party_code_is_present
    party = Party.find_by_party_code(self.party_code)
    if(party.blank?)
      self.errors.add(:party_code, "add party for this party number first")
    end
  end

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :authenticate_user!
  def index
    @entries = Entry.all.page params[:page]
  end

  def new
    @entry = Entry.new
  end

  def show
    @entry = Entry.find(params[:id])
  end

  def edit
    @entry = Entry.find(params[:id])
  end

  def update
    @entry = Entry.find(params[:id])
    if(!@entry.bill.nil? && !@entry.bill.bill_number.empty? && @entry.bill.party_invoice.party_code != entry_params[:party_code])
      flash.now[:error] = "Party invoice created."
      render 'edit' and return
    end
    if @entry.update(entry_params)
      redirect_to @entry
    else
      render 'edit'
    end
  end

  def search
    if(params[:truck_number])
      @entries = Entry.search(params[:truck_number], params[:entry_date])
    elsif(params[:start_date] and params[:end_date])
      @entries = Entry.entries_without_gr_entry_between(params[:start_date], params[:end_date])
    elsif(params[:entry_start_date] and params[:entry_end_date])
      @entries = Entry.entries_without_bill_between(params[:entry_start_date], params[:entry_end_date])
    elsif(params[:invoice_number])
      @entries = Entry.entries_with_invoice_number(params[:invoice_number])
    end
  end

  def create
    @entry = Entry.new(entry_params)

    @entry.save
    if @entry.save
      redirect_to @entry
    else
      render 'new'
    end
  end

  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy

    redirect_to entries_path
  end

  private
  def entry_params
    params.require(:entry).permit!
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_details.html.erb
<div class="show">
  <table class="table table-striped">
    <tr>
      <td class="row-right">
        <strong>Freight 1:</strong>
      </td>
      <td>
        <%= @entry.freight1 %>
      </td>

      <td class="row-right">
        <strong>Cash to Driver:</strong>
      </td>
      <td>
        <%= @entry.cash_to_driver %>
      </td>
    </tr>

    <tr>
      <td class="row-right">
        <strong>Paid to Truck Owner:</strong>
      </td>
      <td>
        <%= @entry.paid_to_truck_owner %>
      </td>
    </tr>
    <tr>

  </table>
</div>

app/views/entries/_list.html.erb
<% if !@entries.nil? and !@entries.empty? %>
  <table class="table table-striped">
    <thead>
    <tr>
      <th>Date</th>
      <th>Truck Number</th>
      <th>Station</th>
      <th>Firm</th>
      <th colspan="2"></th>
    </tr>
    </thead>

    <tbody>
    <% @entries.each do |entry| %>
        <tr>
          <td><%= entry.entry_date %></td>
          <td><%= entry.truck_number %></td>
          <td><%= entry.station %></td>
          <td><%= entry.firm_name %></td>
          <td align="center"><%= link_to 'Show', entry_path(entry), class: 'button small radius' %></td>
          <td><%= link_to 'Edit', edit_entry_path(entry), class: 'button small radius' %></td>
          <% if entry.payment_summary.nil? %>
              <td><%= link_to 'Add Payment Summary', new_entry_payment_summary_path(entry.id), class: 'button small radius' %></td>
          <% else %>
              <td><%= link_to 'Edit Payment Summary', edit_entry_payment_summary_path(entry.id, entry.payment_summary.id), class: 'button small radius' %></td>
          <% end %>
          <% if entry.bill.nil? %>
            <td><%= link_to 'Add Bill Details', new_entry_bill_path(entry.id), class: 'button small radius' %></td>
          <% else %>
            <td><%= link_to 'Edit Bill Details', edit_entry_bill_path(entry.id, entry.bill.id), class: 'button small radius' %></td>
          <% end %>
          <td><%= link_to 'Destroy', entry_path(entry),
                          method: :delete,
                          data: { confirm: 'Are you sure?' }, class: 'button small radius'%></td>
        </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <p>No Entries to Display</p>
<% end %>

app/views/entries/edit.html.erb
<div class="jumbotron">
  <div class="heading">
    <h3>Edit Entry</h3>
  </div>

  <%= form_for :entry, url: entry_path(@entry), method: :patch do |f| %>
      <div class="row shift">
        <%= f.label :date %>
        <%= f.text_field :entry_date, "data-date-format" => "dd/mm/yyyy", class: "form-control datepicker", placeholder: "dd/mm/yyyy" %>
      </div>
      <div class="row shift">
        <%= f.label :truck_number %>
        <%= f.text_field :truck_number, class: "form-control" %>
      </div>

      <div class="row shift">
        <%= f.label :station %>
        <%= f.text_field :station, class: "form-control" %>
      </div>

      <div class="row shift">
        <%= f.label :party_code %>
        <%= f.text_field :party_code, class: "form-control" %>
      </div>

      <div class="row shift">
        <%= f.label :self_advance_1 %>
        <%= f.text_field :self_advance_1, class: "form-control" %>
      </div>

      <div class="row shift">
        <%= f.label :party_advance_2 %>
        <%= f.text_field :party_advance_2, class: "form-control" %>
      </div>

      <div class="row shift">
        <%= f.label :rate1 %>
        <%= f.text_field :rate1, class: "form-control" %>
      </div>

      <div class="row shift">
        <%= f.label :rate2 %>
        <%= f.text_field :rate2, class: "form-control" %>
      </div>

      <div class="row shift">
        <%= f.label :commission %>
        <%= f.text_field :commission, class: "form-control" %>
      </div>

      <%= link_to 'Back', entries_path, class: "btn btn-lg btn-primary" %>
      <%= f.submit class: "btn btn-lg btn-primary"%>

  <% end %>
</div>

app/views/entries/expense_statement_pdf.erb
<div class="party-invoice">
  <div class="expense-statement-content">
    <div class="company-details">
      <h1 class="text-center company-name">JMR LOGISTICS</h1>
      <h3 class="text-center head-office">HEAD OFFICE</h3>
      <h4 class="text-center office-details">Shop No 15, Palla More, Old GT Road, Near Wine Shop, Alipur, Delhi-110036</h4>
      <h4 class="text-center office-details">E-mail: jmrlogistics16@gmail.com</h4>
      <h4 class="text-center office-details">Phone: 9212666550, 9910680644, 9999778668</h4>
      <h4 class="text-center report-title">Expense Statement</h4>
    </div>
  </div>
  <div class="big-font space-mx invoice-statement">
    <table class="table table-condensed">
      <tbody>
      <tr class="table-header">
        <td style="width:12%">Invoice Date</td>
        <td style="width:9%">Invoice Number</td>
        <td style="width:10%">Advance to Owner (Rs)</td>
        <td style="width:9%">Cash to Driver (Rs)</td>
        <td style="width:10%">Balance Payment</td>
        <td style="width:10%">Total</td>
        <td style="width:14%">Truck Number</td>
        <td style="width:12%">Date of Dispatch</td>
        <td style="width:14%">Truck Owner</td>
      </tr>
      <% entries.each do |entry| %>
        <tr>
          <td style="width:12%"><%= entry.invoice_date %></td>
          <td style="width:9%"><%= entry.invoice_number %></td>
          <td style="width:10%"><%= number_to_indian_currency(entry.self_advance_1, text: '') %></td>
          <td style="width:9%"><%= number_to_indian_currency(entry.cash_to_driver, text: '') %></td>
          <td style="width:10%"><%= number_to_indian_currency(entry.paid_to_truck_owner, text: '') %></td>
          <td style="width:10%"><%= number_to_indian_currency(entry.self_advance_1 + entry.cash_to_driver + entry.paid_to_truck_owner, text: '') %></td>
          <td style="width:14%"><%= entry.truck_number %></td>
          <td style="width:12%"><%= entry.entry_date %></td>
          <td style="width:14%"><%= truncate(entry.get_truck_owner, length: 14) %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/entries/index.html.erb
<div class="jumbotron space">
  <ul class="dropdown-menu search_by" aria-labelledby="dropdownMenu3">
    <li class="dropdown-header">Dropdown header</li>
  </ul>
  <!--<select id="search_by" name="search_by" class="input-md selectpicker pull-right btn btn-primary">-->
    <!--<option selected="">Search By</option>-->
    <!--<option value="Truck Number">Truck Number</option>-->
    <!--<option  value="G R Entry">G R Entry</option>-->
  <!--</select>-->
  <!--<div class="well hidden truck-number">-->
    <!--<%= form_tag entries_path, method: :get, class: "form-inline form-right" do %>-->
      <!--<div class="form-group">-->
        <!--<%= text_field_tag :truck_number, params[:truck_number], class: "form-control" %>-->
      <!--</div>-->
      <!--<div class="form-group">-->
        <!--<%= text_field_tag :entry_date, params[:entry_date], "data-date-format" => "dd/mm/yyyy", class: "form-control datepicker", placeholder: "dd/mm/yyyy" %>-->
      <!--</div>-->
      <!--<%= submit_tag "Search", name: nil, class: "btn btn-primary" %>-->
    <!--<% end %>-->
  <!--</div>-->

  <!--<div class="well hidden search-by-range">-->
    <!--<%= form_tag search_entries_path, method: :get, class: "form-inline form-right" do %>-->
        <!--<div class="form-group">-->
          <!--<%= text_field_tag :start_date, params[:start_date], "data-date-format" => "dd/mm/yyyy", class: "form-control datepicker", placeholder: "dd/mm/yyyy" %>-->
        <!--</div>-->
        <!--<div class="form-group">-->
          <!--<%= text_field_tag :end_date, params[:end_date], "data-date-format" => "dd/mm/yyyy", class: "form-control datepicker", placeholder: "dd/mm/yyyy" %>-->
        <!--</div>-->
        <!--<%= submit_tag "Search", name: nil, class: "btn btn-primary" %>-->
    <!--<% end %>-->
  <!--</div>-->
  <h3>Listing Entries</h3>
  <%= render 'entries/list' %>
  <%= paginate @entries %>
  <div>
    <%= page_entries_info @entries %>
  </div>
</div>

app/views/entries/new.html.erb
<div class="jumbotron">
  <div class="heading">
    <h3>New Entry</h3>
  </div>
  <%= form_for :entry, url: entries_path do |f| %>
      <% if @entry.errors.any? %>
          <div id="error_explanation">
            Please enter valid values
            <ul>
              <% @entry.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
      <div class="row shift">
        <%= f.label :date %>
        <%= f.text_field :entry_date, placeholder: "dd/mm/yyyy", class: 'flatpickr' %>
      </div>
      <div class="row shift">
        <%= f.label :truck_number %>
        <%= f.text_field :truck_number, class: "form-control" %>
      </div>

      <div class="row shift">
        <%= f.label :station %>
        <%= f.text_field :station, class: "form-control" %>
      </div>

      <div class="row shift">
        <%= f.label :party_code %>
        <%= f.text_field :party_code, class: "form-control" %>
      </div>

      <div class="row shift">
        <%= f.label :self_advance_1 %>
        <%= f.text_field :self_advance_1, class: "form-control" %>
      </div>

      <div class="row shift">
        <%= f.label :party_advance_2 %>
        <%= f.text_field :party_advance_2, class: "form-control" %>
      </div>

      <div class="row shift">
        <%= f.label :rate1 %>
        <%= f.text_field :rate1, class: "form-control" %>
      </div>

      <div class="row shift">
        <%= f.label :rate2 %>
        <%= f.text_field :rate2, class: "form-control" %>
      </div>

      <div class="row shift">
        <%= f.label :commission %>
        <%= f.text_field :commission, class: "form-control" %>
      </div>

      <%= link_to 'Back', entries_path, class: 'btn btn-lg btn-primary', data: {tooltip_display: :true, placement: :bottom}  %>
      <%= f.submit class: "btn btn-lg btn-primary", data: {tooltip_display: :true, placement: :bottom} %>
  <% end %>

</div>

app/views/entries/search.html.erb
<ul class="nav nav-tabs nav-justified">
  <li class="active"><a data-toggle="tab" href="#truck-number">By Truck Number</a></li>
  <li><a data-toggle="tab" href="#search-by-range">By G R Entry</a></li>
  <li><a data-toggle="tab" href="#search-by-bill">By Bill</a></li>
  <li><a data-toggle="tab" href="#search-by-invoice-number">By Invoice Number</a></li>
</ul>
<div class="tab-content tab-content-padding-top">

  <div id="truck-number" class="tab-pane fade in active">
    <%= form_tag search_entries_path, method: :get, class: "form-inline" do %>
        <div class="form-group">
          <%= text_field_tag :truck_number, params[:truck_number], class: "form-control" %>
        </div>
        <div class="form-group">
          <%= text_field_tag :entry_date, params[:entry_date], "data-date-format" => "dd/mm/yyyy", class: "form-control datepicker", placeholder: "dd/mm/yyyy" %>
        </div>
        <%= submit_tag "Search", name: nil, class: "btn btn-primary" %>
    <% end %>
  </div>

  <div id="search-by-range" class="tab-pane fade">
    <%= form_tag search_entries_path, method: :get, class: "form-inline" do %>
        <div class="form-group mx-sm-3">
          <%= text_field_tag :start_date, params[:start_date], "data-date-format" => "dd/mm/yyyy", class: "form-control datepicker", placeholder: "dd/mm/yyyy" %>
        </div>
        <div class="form-group mx-sm-3">
          <%= text_field_tag :end_date, params[:end_date], "data-date-format" => "dd/mm/yyyy", class: "form-control datepicker", placeholder: "dd/mm/yyyy" %>
        </div>
        <%= submit_tag "Search", name: nil, class: "btn btn-primary" %>
    <% end %>
  </div>

  <div id="search-by-bill" class="tab-pane fade">
    <%= form_tag search_entries_path, method: :get, class: "form-inline" do %>
        <div class="form-group mx-sm-3">
          <%= text_field_tag :entry_start_date, params[:entry_start_date], "data-date-format" => "dd/mm/yyyy", class: "form-control datepicker", placeholder: "dd/mm/yyyy" %>
        </div>
        <div class="form-group mx-sm-3">
          <%= text_field_tag :entry_end_date, params[:entry_end_date], "data-date-format" => "dd/mm/yyyy", class: "form-control datepicker", placeholder: "dd/mm/yyyy" %>
        </div>
        <%= submit_tag "Search", name: nil, class: "btn btn-primary" %>
    <% end %>
  </div>

  <div id="search-by-invoice-number" class="tab-pane fade">
    <%= form_tag search_entries_path, method: :get, class: "form-inline" do %>
        <div class="form-group">
          <%= text_field_tag :invoice_number, params[:invoice_number], class: "form-control" %>
        </div>
        <%= submit_tag "Search", name: nil, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<h3>Search Results</h3>
<%= render 'entries/list' %>

app/views/entries/show.html.erb
<div class="jumbotron">
  <div class="heading-2" style="text-align:right;width:100%">
    <span style="float:left">
      <h4>Entry</h4>
    </span>
    <p style="float:right; font-size:13px;"><%= link_to 'Edit Entry', edit_entry_path(@entry) %></p>
  </div>
  <div class="show">
    <table class="table table-striped">
      <tr>
        <td class="row-right">
          <strong>Date:</strong>
        </td>
        <td>
          <%= @entry.entry_date %>
        </td>
        <td class="row-right">
          <strong>Commission:</strong>
        </td>
        <td>
          <%= @entry.commission %>
        </td>
    </tr>

      <tr>
        <td class="row-right">
          <strong>Truck Number:</strong>
        </td>
        <td>
          <%= @entry.truck_number %>

        </td>
        <td class="row-right">
          <strong>Self Advance:</strong>
        </td>
        <td>
          Rs <%= @entry.self_advance_1 %>
        </td>
      </tr>
      <tr>
        <td class="row-right">
          <strong>Station:</strong>
        </td>
        <td>
          <%= @entry.station %>
        </td>
        <td class="row-right">
          <strong>Party Advance:</strong>
        </td>
        <td>
          Rs <%= @entry.party_advance_2 %>
        </td>
      </tr>
      <tr>
        <td class="row-right">
          <strong>Party Code:</strong>
        </td>
        <td>
          <%= @entry.party_code %>
        </td>
        <td class="row-right">
          <strong>Firm:</strong>
        </td>
        <td>
          <%= @entry.firm_name %>
        </td>
      </tr>

      <tr>
        <td class="row-right">
          <strong>Rate1:</strong>
        </td>
        <td>
          Rs <%= @entry.rate1 %>
        </td>
        <td class="row-right">
          <strong>Rate2:</strong>
        </td>
        <td>
          Rs <%= @entry.rate2 %>
        </td>
      </tr>
    </table>
  </div>
  <% if @entry.payment_summary.nil? %>
    <div>
      <div class="heading-2">
        <h4>G R Entry</h4>
      </div>
      <div class="align-center">
        <%= link_to 'Add Payment Summary', new_entry_payment_summary_path(@entry.id) %>
      </div>
    </div>
  <% else %>
    <div>
      <div class="heading-2" style="text-align:right;width:100%">
        <span style="float:left">
          <h4>G R Entry</h4>
        </span>
        <p style="float:right; font-size:13px;"><%= link_to 'Edit Payment Summary', edit_entry_payment_summary_path(@entry.id, @entry.payment_summary) %></p>
      </div>
      <%= render 'payment_summaries/show' %>
    </div>

    <div>
      <div class="heading-2">
        <h4>Payments</h4>
      </div>
      <%= render 'entries/details' %>
    </div>
  <% end %>

  <% if @entry.bill.nil? %>
    <div>
      <div class="heading-2">
        <h4>Bill Details</h4>
      </div>
      <div class="align-center">
        <%= link_to 'Add Bill', new_entry_bill_path(@entry.id) %>
      </div>
    </div>
  <% else %>
    <div>
      <div class="heading-2" style="text-align:right;width:100%">
        <span style="float:left">
          <h4>Bill Details</h4>
        </span>
        <p style="float:right; font-size:13px;"><%= link_to 'Edit Bill Details', edit_entry_bill_path(@entry.id, @entry.bill.id) %></p>
      </div>
      <%= render 'bills/show' %>
    </div>
  <% end %>
  <% if !@entry.payment_summary.nil? %>
    <% if @entry.company.nil? %>
      <button type="button" class="btn btn-lg btn-primary" data-toggle="modal" data-target="#myModal">Download PDF</button>
    <% else %>
      <%= link_to "Download PDF",
        entry_download_path(@entry, format: "pdf"),
        target: "_blank",
        class: "btn btn-lg btn-primary" %>
    <% end %>

    <div id="myModal" class="modal fade" role="dialog">
      <div class="modal-dialog">

          <!-- Modal content-->
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Select Company</h4>
          </div>
          <div class="modal-body">
            <%= form_for :entry, url: entry_download_path(@entry, format: "pdf"), formtarget: :_blank, method: :get do |f| %>
                <%= radio_button_tag(:company, "jmr", true) %>
                <%= label_tag(:jmr, "JMR Logistics") %>
                <br>
                <%= radio_button_tag(:company, "gujarat", false) %>
                <%= label_tag(:gujarat, "R.K. Gujarat Road Carrier") %>
                <br>
                <td><%= f.submit 'Download', class: "btn btn-lg btn-primary",  input_html: {"data-dismiss": "modal", "aria-hidden": "true" } %></td>
            <% end %>
          </div>
        </div>

      </div>
    </div>

<% end %>

  <%= link_to 'Back', entries_path, class: "btn btn-lg btn-primary" %>
</div>