config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "entries#index"
  resources :truck_details
  resources :payment_receipts
  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end
  resources :parties, concerns: :paginatable do
    resources :opening_balances
  end
  get 'parties/party_by_code/:party_code', to: 'parties#party_by_code'
  resources :party_invoices, concerns: :paginatable do
    member do
      patch :unlock
      put :unlock
    end
    resources :bills
    get 'download', on: :member, to: 'downloads#party_invoice_show'
  end
  get 'download_statement', to: 'downloads#invoice_statement_show'
  get 'download_expenses', to: 'downloads#expenses_show'
  get 'download_ledger', to: 'downloads#ledger_show'
  get 'download_parties_balance', to: 'downloads#balance_for_parties'
  resources :entries, concerns: :paginatable do
    resource :download, only: [:show]
    resources :payment_summaries
    resources :bill_entries
    resources :bills
    collection do
      get 'search'
    end
    get 'download', on: :member
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/truck_details.rb
class TruckDetails < ApplicationRecord
  validates :truck_number, presence: true,
            length: { maximum: 15 }, uniqueness: true
  validates :truck_owner, presence: true,
            length: { maximum: 25 }
end

app/controllers/truck_details_controller.rb
class TruckDetailsController < ApplicationController
  before_action :authenticate_user!
  def index
    @truck_details = TruckDetails.all.page params[:page]
  end

  def new
    @truck_detail = TruckDetails.new
  end

  def show
    @truck_detail = TruckDetails.find(params[:id])
  end

  def create
    @truck_detail = TruckDetails.new(truck_detail_params)

    if @truck_detail.save
      redirect_to @truck_detail
    else
      render 'new'
    end
  end

  def edit
    @truck_detail = TruckDetails.find(params[:id])
  end

  def update
    @truck_detail = TruckDetails.find(params[:id])

    if @truck_detail.update(truck_detail_params)
      redirect_to @truck_detail
    else
      render 'edit'
    end
  end

  def destroy
    @truck_detail = TruckDetails.find(params[:id])
    @truck_detail.destroy

    redirect_to truck_details_path
  end

  private
  def truck_detail_params
    params.require(:truck_detail).permit!
  end
end

app/helpers/truck_details_helper.rb
module TruckDetailsHelper
end

app/views/truck_details/_list.html.erb
<% if !@truck_details.nil? and !@truck_details.empty? %>
  <table class="table table-striped">
    <thead>
    <tr>
      <th>Truck Number</th>
      <th>Truck Owner</th>
      <th colspan="2"></th>
    </tr>
    </thead>

    <tbody>
    <% @truck_details.each do |truck_detail| %>
        <tr>
          <td><%= truck_detail.truck_number %></td>
          <td><%= truck_detail.truck_owner %></td>
          <td><%= link_to 'Edit', edit_truck_detail_path(truck_detail), class: 'button small radius' %></td>
          <td><%= link_to 'Destroy', truck_detail_path(truck_detail),
                          method: :delete,
                          data: { confirm: 'Are you sure?' }, class: 'button small radius'%></td>
        </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <p>No Truck Details to Display</p>
<% end %>

app/views/truck_details/edit.html.erb
<div class="jumbotron">
  <div class="heading">
    <h3>Edit Truck Detail</h3>
  </div>

  <%= form_for :truck_detail, url: truck_detail_path(@truck_detail), method: :patch do |f| %>
      <div class="row shift">
        <%= f.label :truck_number %>
        <%= f.text_field :truck_number, class: "form-control" %>
      </div>

      <div class="row shift">
        <%= f.label :truck_owner %>
        <%= f.text_field :truck_owner, class: "form-control" %>
      </div>

      <%= link_to 'Back', truck_details_path, class: "btn btn-lg btn-primary" %>
      <%= f.submit class: "btn btn-lg btn-primary"%>

  <% end %>
</div>

app/views/truck_details/index.html.erb
<div class="jumbotron space">
  <ul class="dropdown-menu search_by" aria-labelledby="dropdownMenu3">
    <li class="dropdown-header">Dropdown header</li>
  </ul>
  <div class="heading-2" style="text-align:right;width:100%">
    <span style="float:left">
      <h3>Truck details</h3>
    </span>
    <p style="float:right; font-size:13px;"><%= link_to 'New Truck Details', new_truck_detail_path %></p>
  </div>
  <%= render 'truck_details/list' %>
  <%= paginate @truck_details %>
  <div>
    <%= page_entries_info @truck_details %>
  </div>
</div>

app/views/truck_details/new.html.erb
<div class="jumbotron">
  <div class="heading">
    <h3>Add Truck Details</h3>
  </div>
  <%= form_for :truck_detail, url: truck_details_path do |f| %>
      <% if @truck_detail.errors.any? %>
          <div id="error_explanation">
            Please enter valid values
            <ul>
              <% @truck_detail.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
      <div class="row shift">
        <%= f.label :truck_number %>
        <%= f.text_field :truck_number, class: "form-control" %>
      </div>

      <div class="row shift">
        <%= f.label :truck_owner %>
        <%= f.text_field :truck_owner, class: "form-control" %>
      </div>

      <%= link_to 'Back', truck_details_path, class: 'btn btn-lg btn-primary' %>
      <%= f.submit class: "btn btn-lg btn-primary"%>
  <% end %>

</div>

app/views/truck_details/show.html.erb
<div class="jumbotron">
  <div class="heading-2">
    <h4>Truck Detail</h4>
  </div>
  <div class="show">
    <table class="table table-striped">
      <tr>
        <td class="row-right">
          <strong>Truck Number:</strong>
        </td>
        <td>
          <%= @truck_detail.truck_number %>

        </td>
        <td class="row-right">
          <strong>Truck Owner:</strong>
        </td>
        <td>
          <%= @truck_detail.truck_owner %>
        </td>
      </tr>
    </table>
  </div>
  <%= link_to 'Back', entries_path, class: "btn btn-lg btn-primary" %>
</div>