config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "entries#index"
  resources :truck_details
  resources :payment_receipts
  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end
  resources :parties, concerns: :paginatable do
    resources :opening_balances
  end
  get 'parties/party_by_code/:party_code', to: 'parties#party_by_code'
  resources :party_invoices, concerns: :paginatable do
    member do
      patch :unlock
      put :unlock
    end
    resources :bills
    get 'download', on: :member, to: 'downloads#party_invoice_show'
  end
  get 'download_statement', to: 'downloads#invoice_statement_show'
  get 'download_expenses', to: 'downloads#expenses_show'
  get 'download_ledger', to: 'downloads#ledger_show'
  get 'download_parties_balance', to: 'downloads#balance_for_parties'
  resources :entries, concerns: :paginatable do
    resource :download, only: [:show]
    resources :payment_summaries
    resources :bill_entries
    resources :bills
    collection do
      get 'search'
    end
    get 'download', on: :member
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">JMR Logistics</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'New Entry', new_entry_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Truck List', truck_details_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'New Party', new_party_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Party List', parties_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Party Invoices', party_invoices_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Payment Receipts List', payment_receipts_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Invoice Statement', "#", "data-toggle": "modal", "data-target": "#invoiceStatementModal", class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Expense Statement', "#", "data-toggle": "modal", "data-target": "#expenseStatementModal", class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Ledger', "#", "data-toggle": "modal", "data-target": "#ledgerModal", class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Balance for Parties', "#", "data-toggle": "modal", "data-target": "#balanceForPartyModal", class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Search', search_entries_path, class: 'nav-link' %>
      </li>
      <% if user_signed_in? %>
          <li>
            <%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'nav-link') %>
          </li>
        <% else %>
          <li>
            <%= link_to('Login', new_user_session_path, class: 'nav-link')  %>
          </li>
        <% end %>
    </ul>
  </div>
</nav>